name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          docker buildx build \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f amazonlinux.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta \
            .
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
          docker buildx build \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f alpine.Dockerfile \
            -t truemark/git-crypt:beta-musl-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta-musl \
            .
          IMAGE="truemark/git-crypt:beta-musl-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-musl-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-musl-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-musl-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
      - uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            *.tar.gz
