name: release

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-amazonlinux-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f amazonlinux-2.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2 \
            -t truemark/git-crypt:beta-amazonlinux-2 \
            .
  build-amazonlinux-2022:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f amazonlinux-2022.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2022 \
            -t truemark/git-crypt:beta-amazonlinux-2022 \
            .
  build-ubuntu-focal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-focal.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-focal \
            -t truemark/git-crypt:beta-ubuntu-focal \
            .
  build-ubuntu-jammy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-jammy.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-jammy \
            -t truemark/git-crypt:beta-ubuntu-jammy \
            .
  build-debian-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f debian-buster.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-buster \
            -t truemark/git-crypt:beta-debian-buster \
            .
  build-debian-bullseye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f debian-bullseye.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bullseye \
            -t truemark/git-crypt:beta-debian-bullseye \
            .
  build-debian-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f debian-bookworm.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bookworm \
            -t truemark/git-crypt:beta-debian-bookworm \
            .
  build-alpine-316:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f alpine-3.16.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.16 \
            -t truemark/git-crypt:beta-alpine-3.16 \
            .
  build-alpine-317:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f alpine-3.17.Dockerfile \
            -t truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.17 \
            -t truemark/git-crypt:beta-alpine-3.17 \
            .
  images:
    needs: [build-amazonlinux-2022, build-amazonlinux-2, build-ubuntu-jammy, build-ubuntu-focal, build-debian-bookworm, build-debian-bullseye, build-debian-buster, build-alpine-317, build-alpine-316]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_VERSION=$(curl -sSL https://api.github.com/repos/git/git/tags | jq -r "[.[].name | select(contains(\"-rc\") | not)] | .[0] | sub(\"v\";\"\")")
          echo "GIT_VERSION=${GIT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_VERSION}"
      - name: Build
        run: |
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2" ARCH="amd64" FILE="git-crypt-amazonlinux-2-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2" ARCH="arm64" FILE="git-crypt-amazonlinux-2-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2022" ARCH="amd64" FILE="git-crypt-amazonlinux-2022-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-amazonlinux-2022" ARCH="arm64" FILE="git-crypt-amazonlinux-2022-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-focal" ARCH="amd64" FILE="git-crypt-ubuntu-focal-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-focal" ARCH="arm64" FILE="git-crypt-ubuntu-focal-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-jammy" ARCH="amd64" FILE="git-crypt-ubuntu-jammy-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-ubuntu-jammy" ARCH="arm64" FILE="git-crypt-ubuntu-jammy-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-buster" ARCH="amd64" FILE="git-crypt-debian-buster-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-buster" ARCH="arm64" FILE="git-crypt-debian-buster-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bullseye" ARCH="amd64" FILE="git-crypt-debian-bullseye-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bullseye" ARCH="arm64" FILE="git-crypt-debian-bullseye-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bookworm" ARCH="amd64" FILE="git-crypt-debian-bookworm-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-debian-bookworm" ARCH="arm64" FILE="git-crypt-debian-bookworm-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.16" ARCH="amd64" FILE="git-crypt-alpine-3.16-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.16" ARCH="arm64" FILE="git-crypt-alpine-3.16-arm64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.17" ARCH="amd64" FILE="git-crypt-alpine-3.17-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-${GIT_CRYPT_VERSION}-alpine-3.17" ARCH="arm64" FILE="git-crypt-alpine-3.17-arm64" ./getlayer.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            git-crypt-*
