name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Git Crypt Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]") >> $GITHUB_OUTPUT
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f amazonlinux.Dockerfile \
            -t truemark/git-crypt:beta-amazonlinux-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta-amazonlinux \
            .
          IMAGE="truemark/git-crypt:beta-amazonlinux-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-amazonlinux-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-amazonlinux-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-amazonlinux-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f alpine.Dockerfile \
            -t truemark/git-crypt:beta-alpine-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta-alpine \
            .
          IMAGE="truemark/git-crypt:beta-alpine-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-alpine-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-alpine-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-alpine-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-focal.Dockerfile \
            -t truemark/git-crypt:beta-ubuntu-focal-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta-ubuntu-focal \
            .
          IMAGE="truemark/git-crypt:beta-ubuntu-focal-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-ubuntu-focal-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-ubuntu-focal-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-ubuntu-focal-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-jammy.Dockerfile \
            -t truemark/git-crypt:beta-ubuntu-jammy-${GIT_CRYPT_VERSION} \
            -t truemark/git-crypt:beta-ubuntu-jammy \
            .
          IMAGE="truemark/git-crypt:beta-ubuntu-jammy-${GIT_CRYPT_VERSION}" ARCH="amd64" FILE="git-crypt-ubuntu-jammy-${GIT_CRYPT_VERSION}-linux-amd64.tar" ./getlayer.sh
          IMAGE="truemark/git-crypt:beta-ubuntu-jammy-${GIT_CRYPT_VERSION}" ARCH="arm64" FILE="git-crypt-ubuntu-jammy-${GIT_CRYPT_VERSION}-linux-arm64.tar" ./getlayer.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: "*.gz"
          release_name: beta-${{env.GIT_CRYPT_VERSION}}
          overwrite: true
      - uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            *.tar.gz
