name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Run at 4PM UTC every Monday
    - cron: '0 16 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export GIT_CRYPT_VERSION=$(curl -sSL https://api.github.com/repos/AGWA/git-crypt/tags | jq -r "[.[].name | select(contains(\"debian\") | not)] | .[0]")
          echo "GIT_CRYPT_VERSION=${GIT_CRYPT_VERSION}" >> $GITHUB_ENV
          echo "Version: ${GIT_CRYPT_VERSION}"
          export TAG_EXISTS=$(curl -sSL https://api.github.com/repos/truemark/git-crypt-docker/tags | jq -r ".[].name == \"${GIT_CRYPT_VERSION}\"")
          echo "TAG_EXISTS=${TAG_EXISTS}" >> $GITHUB_ENV
          echo "Exists: ${TAG_EXISTS}"
      - name: Build
        if: ${{ env.TAG_EXISTS != 'true' }}
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f amazonlinux.Dockerfile \
            -t truemark/git-crypt:${GIT_CRYPT_VERSION}-amazonlinux \
            -t truemark/git-crypt:amazonlinux \
            .
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-amazonlinux" ARCH="amd64" FILE="git-crypt-amazonlinux-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-amazonlinux" ARCH="arm64" FILE="git-crypt-amazonlinux-arm64" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f alpine.Dockerfile \
            -t truemark/git-crypt:${GIT_CRYPT_VERSION}-alpine \
            -t truemark/git-crypt:alpine \
            .
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-alpine" ARCH="amd64" FILE="git-crypt-alpine-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-alpine" ARCH="arm64" FILE="git-crypt-alpine-arm64" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-focal.Dockerfile \
            -t truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-focal \
            -t truemark/git-crypt:ubuntu-focal \
            .
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-focal" ARCH="amd64" FILE="git-crypt-ubuntu-focal-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-focal" ARCH="arm64" FILE="git-crypt-ubuntu-focal-arm64" ./getlayer.sh
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg GIT_CRYPT_VERSION="${GIT_CRYPT_VERSION}" \
            -f ubuntu-jammy.Dockerfile \
            -t truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-jammy \
            -t truemark/git-crypt:ubuntu-jammy \
            -t truemark/git-crypt:ubuntu \
            .
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-jammy" ARCH="amd64" FILE="git-crypt-ubuntu-jammy-amd64" ./getlayer.sh
          IMAGE="truemark/git-crypt:${GIT_CRYPT_VERSION}-ubuntu-jammy" ARCH="arm64" FILE="git-crypt-ubuntu-jammy-arm64" ./getlayer.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ env.TAG_EXISTS != 'true' }}
        with:
          name: files
          path: |
            git-crypt-*
      - name: Upload binaries to release
        if: ${{ env.TAG_EXISTS != 'true' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: |
            git-crypt-*
          release_name: ${{env.GIT_CRYPT_VERSION}}
          tag: ${{env.GIT_CRYPT_VERSION}}
          overwrite: true
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
